# Generated by Django 6.0.4 on 2026-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Фио')),
                ('mail', models.CharField(max_length=250, verbose_name='Эл.Почта')),
                ('sex', models.CharField(max_length=10, verbose_name='Пол')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
        ),
    ]
